deploy_manual_job:
  stage: deploy
  image: alpine:latest
  before_script:
    - apk update && apk add --no-cache openssh-client sshpass git docker-cli docker-compose
  script:
    - echo "🚀 Starting deployment on live server 110.34.2.30"
    - mkdir -p ~/.ssh
    - echo -e "Host live-server\n  HostName 110.34.2.30\n  Port 23\n  User devops" > ~/.ssh/config
    - chmod 600 ~/.ssh/config
    - |
      sshpass -p "$shm_server_pwd" ssh -o StrictHostKeyChecking=no devops@110.34.2.30 -p 23 "
        set -e
        echo '🔧 Creating deployment directory...'
        mkdir -p /home/hsmdevops/test
        cd /home/hsmdevops/test

        echo 'Cloning or pulling latest code...'
        if [ -d .git ]; then
          git pull
        else
          git clone -b main https://oauth2:${GITLAB_PAT}@gitlab.com/aswinkarki-group/Devops.git .
        fi

        echo '🚢 Building & starting Docker containers...'
        cd /home/hsmdevops/test/devOps/
        docker compose -f docker-compose.yml up -d --build

        echo '📦 Checking container status...'
        docker ps -a

        echo '📄 Displaying recent logs...'
        docker compose -f Devops/devOps/docker-compose.yml logs --tail=50 || true

        echo '✅ Deployment completed and cleanup done on live server.'
      "
  only:
    - main
  when: manual
