stages:
  - deploy

deploy_manual_job:
  stage: deploy
  image: alpine:latest  # lightweight image with SSH
  before_script:
    - apk update && apk add --no-cache openssh-client sshpass git

  script:
    - echo "Starting deployment on live server 110.34.2.30"
    - mkdir -p ~/.ssh
    - |
      echo -e "Host live-server\n  HostName 118.34.2.38\n  Port 23\n  User devops" > ~/.ssh/config
    - chmod 600 ~/.ssh/config
    - |
      sshpass -p "shm_server_pwd" ssh -o StrictHostKeyChecking=no  -p 23 devops@110.34.2.30 "
        mkdir -p /home/hsmdevops/testt
        cd /home/hsmdevops/testt
        echo 'Cloning repository using GitLab access token...'
        git clone -b main https://oauth2:${GITLAB_PAT}@gitlab.com/aswinkarki-group/Devops.git . || true
        echo 'Building & starting Docker containers...'
        docker-compose -f docker-compose.yml up -d --build
        echo 'Checking container status...'
        docker ps -a 
        echo 'Displaying recent logs...'
        docker compose logs --tail=50
        echo 'Deployment completed and cleanup done on live server.'
      "

  only:
    - main

  when: manual
